version: '3.8'

services:
  trading-bot:
    build: .
    container_name: ai_trading_bot
    environment:
      - DERIV_APP_ID=${DERIV_APP_ID}
      - DERIV_TOKEN=${DERIV_TOKEN}
    volumes:
      - .:/app
    ports:
      - "8501:8501"  # Streamlit dashboard
    restart: unless-stopped

  redis:  # For experience replay storage
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: