account:
  initial_balance: 1000.0

deriv:
  app_id: "YOUR_APP_ID"
  token: "YOUR_TOKEN"
  symbols: ["R_100"]
  
strategy:
  timeframe: "5m"
  base_confidence: 0.65
  data_window: 100

risk:
  max_daily_loss: 5.0

learning:
  replay_buffer: 10000
  batch_size: 32
  epsilon_decay: 0.995
  model_path: "models/latest.model"

processing:
  window_size: 20

execution:
  interval: 60  # Seconds